#!bin/bash

javac ./practice/Product.java
javac ./practice/VendingMachine.java

javac ./practice/impl/BottleOfWater.java
javac ./practice/impl/EPackage.java
javac ./practice/impl/HotDrinkVM.java
javac ./practice/impl/HotDrink.java
javac ./practice/impl/WaterVendingMachine.java

javac ./practice/ProductMain.java

echo "Run file?"
decision=""
read decision
if [[ $decision = "y" ]]; then
	java practice.ProductMain
fi

